name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  docker-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image (alpine)
        run: docker build -t hello-devops:alpine .

      - name: Test output equals expected
        run: |
          set -euo pipefail
          out=$(docker run --rm hello-devops:alpine)
          echo "Container output: $out"
          test "$out" = "Hello from inside Docker!"

      - name: Ensure container runs as non-root
        run: |
          set -euo pipefail
          uid=$(docker run --rm --entrypoint sh hello-devops:alpine -c 'id -u')
          echo "UID inside container: $uid"
          test "$uid" -ne 0

